name: Portal - APP

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "App/**"
      - ".github/workflows/Portal-app.yml"

env:
  # ApiUrl: https://mobile-api-dev-a2pilg7y3a-ew.a.run.app/api
  GCP_PROJECT: engineering-thesis-346319
  CloudStorageBucket: ibigworld-ath

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ env.GCP_PROJECT }}
          credentials_json: ${{ secrets.GCP_SA_SECRET }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      # - uses: microsoft/variable-substitution@v1
      #   with:
      #     files: "Mobile/app/src/config.json"
      #   env:
      #     baseUrl: ${{ env.ApiUrl }}

      # - name: Read config.json
      #   run: "cat Mobile/app/src/config.json"  

      - name: Build and deploy frontend to static GCP Cloud Storage
        id: deploy
        run: |
          cd App
          yarn install
          yarn build
          gsutil web set -m index.html -e index.html gs://${{env.CloudStorageBucket}}/
          gsutil -h "Cache-Control:public, max-age=60, no-transform" -m rsync -d -r -j js,html,map,css ./build gs://${{env.CloudStorageBucket}}/

  tag:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    continue-on-error: false

    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main