name: Portal - Database

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "Server/IBigDataPortal/Portal.Database/**"
      - ".github/workflows/Portal-database.yml"


jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2 
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install EF Tool 
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef

      - name: Generate migration script
        run: dotnet ef migrations script -s ./Portal -p ./Portal.Database --output "migration-script.sql" --idempotent
        working-directory: ./Server/IBigDataPortal

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v1 
        with:
          server-name: ibigdataportaldatabase.database.windows.net
          connection-string: ${{ secrets.AZURE_CONNECTION_STRING }}
          sql-file: ./Server/IBigDataPortal/migration-script.sql
