# # This is a basic workflow to help you get started with Actions

name: Portal - API

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "Server/**"
      - ".github/workflows/Portal-api.yml"
  
env:
  AuthenticationType: "Auth0"
  Origins: "*"
  GCP_PROJECT: engineering-thesis-346319
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_SECRET }}
          export_default_credentials: true
      - uses: actions/checkout@v2

      - uses: microsoft/variable-substitution@v1
        working-directory: ./Server/IBigDataPortal 
        with:
          files: "Portal/appsettings.json"
        env:
          ConnectionStrings.SqlDataContext: ${{ secrets.GCP_CONNECTION_STRING }}
          
      - name: Build the Docker image
        working-directory: ./Server/IBigDataPortal
        run: docker build -f Dockerfile -t eu.gcr.io/${{ env.GCP_PROJECT }}/portal-api-prod . 
        
      - name: Configure Docker to use Google Cloud Platform
        run: gcloud auth configure-docker --quiet
        
      - name: Docker push image
        run: docker push eu.gcr.io/${{ env.GCP_PROJECT }}/portal-api-prod
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: false
    
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_SECRET }}
          export_default_credentials: true
          
      - name: Cloud run deploy
        run: gcloud run deploy portal-api-prod --image eu.gcr.io/${{ env.GCP_PROJECT }}/portal-api-prod --region=europe-west1 --project=${{ env.GCP_PROJECT }} --memory=1024M --max-instances=10 --cpu=2 --timeout=120 --port=80
      
      - name: Cloud run serve traffic
        run: gcloud run services update-traffic portal-api-prod --to-latest --platform=managed --region=europe-west1
