name: Portal - APP

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "App/**"
      - ".github/workflows/Portal-app.yml"

env:
  ApiUrl: https://portal-api-prod-etflayreta-ew.a.run.app
  GCP_PROJECT: engineering-thesis-346319
  CloudStorageBucket: ibigworld-ath.com

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ env.GCP_PROJECT }}
          credentials_json: ${{ secrets.GCP_SA_SECRET }}
          
      - uses: microsoft/variable-substitution@v1
        with:
          files: "App/src/authenticationConfig.json"
        env:
          baseUrl: ${{ env.ApiUrl }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build and deploy frontend to static GCP Cloud Storage
        id: deploy
        run: |
          cd App
          yarn install
          yarn build
          gsutil web set -m index.html -e index.html gs://${{env.CloudStorageBucket}}/
          gsutil -h "Cache-Control:public, max-age=60, no-transform" -m rsync -d -r -j js,html,map,css ./build gs://${{env.CloudStorageBucket}}/
          gcloud compute url-maps invalidate-cdn-cache loadbalancer --path '/*' --async

  tag:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    continue-on-error: false

    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main