name: Portal - API integration tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "Server/**"
      - ".github/workflows/Portal-api-integration-tests.yml"

concurrency: connection-with-azure-testing-db

jobs:
  tests:
    runs-on: ubuntu-latest
    
    services:
      sql.data:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: P@$$w0rd
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"

    steps:
      - uses: actions/checkout@v2

      - name: Replace connection string
        uses: microsoft/variable-substitution@v1
        with:
          files: ./Server/IBigDataPortal/Portal/appsettings.json
        env:
          connectionStrings.SqlTestingConnectionString: Server=localhost,1433; Database=PortalAPITesting; User Id='SA'; Password='P@$$w0rd'

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.0.x
            6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Server/IBigDataPortal/Portal.IntegrationTests

      - name: Build
        run: dotnet build --no-restore
        working-directory: ./Server/IBigDataPortal/Portal.IntegrationTests

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./Server/IBigDataPortal/Portal.IntegrationTests